---
- hosts: all
  remote_user: netris
  become: yes
  gather_facts: no
  gather_subset: '!all'
  vars_files:
  - roles/lemp/vars/main.yml
  vars:
    app_name: nginx-proxy
  roles:
  - common
  - docker
  - nginx-docker
