---
- hosts: all
  remote_user: netris
  become: yes
  gather_facts: no
  vars_files:
  - roles/lemp/vars/main.yml
  vars:
    app_name: nginx-proxy
  pre_tasks:
  - set_fact:
      ansible_distribution_major_version: "8"
  roles:
  - common
  - docker
  - nginx-docker
