---
- name: Install Debian Specific Packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
  - python3
  - apt-transport-https
  - ca-certificates
  - gnupg
  - xz-utils
  - lsb-release
  - python3-mysqldb
  - python3-simplejson
  - python3-pip
  - python3-setuptools

- name: Create Symlinks for Python and PIP
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    state: link
  loop:
  - { src: '/usr/bin/python3', dest: '/usr/bin/python' }
  - { src: '/usr/bin/pip3', dest: '/usr/bin/pip' }
