---
- name: Install Debian Specific Packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
  - python3
  - python3-mysqldb
  - python3-simplejson
  - python3-pip
  - python3-setuptools
