---
- name: Create directories
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items:
  - { path: '{{ instance_root }}', state: 'directory' }
  
- name: Copy template files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
  - { src: 'docker-compose.yml.j2', dest: '{{ instance_root }}/docker-compose.yml' }
  - { src: 'wp-config.php.j2', dest: '{{ instance_root }}/wp-config.php' }
    
- name: Run Docker containers with compose
  command: "chdir={{ instance_root }} docker-compose up -d"
  
- name: Create new dir in container
  command: "docker exec -d {{ wp_container }} mkdir -p {{ wp_config_dir }}"
  
- name: Move wp-config file to new dir
  command: "docker exec -d {{ wp_container }} /bin/bash -c 'cp -n {{ html_root }}/wp-config.php {{ wp_config_dir }}/'"
  
- name: Move wp-config File
  command: "docker exec -d {{ wp_container }} /bin/bash -c 'cp -n {{ html_root }}/wp-config-docker.php {{ wp_config_dir }}/wp-config.php'"
  
- name: Copy dummy wp-config
  command: "docker cp {{ instance_root }}/wp-config.php {{ wp_container }}:{{ html_root }}/"
  
- name: Remove default themes
  command: "docker exec -d {{ wp_container }} /bin/bash -c 'rm -rf {{ html_root }}/wp-content/themes/twenty*'"
  
- name: Change permissions on html dir
  command: "docker exec -d {{ wp_container }} /bin/bash -c 'chown -R www-data:www-data {{ html_root }}'"
