---
- name: Add Docker GPG key.
  apt_key:
    key: "{{ docker_gpg_apt_key_url }}"
    state: present

- name: Add Docker ce repo
  get_url:
    url: "{{ docker_apt_repo_url }}"
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644

- name: Install Docker
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items:
  - { name: 'docker-{{ docker_edition }}', state: 'present' }
