---
- name: Add Docker GPG key.
  apt_key:
    key: "{{ docker_gpg_apt_key_url }}"
    state: present

- name: Install Docker
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  loop:
  - { name: 'docker-{{ docker_edition }}', state: 'present' }
