---
- name: Add Docker GPG key.
  rpm_key:
    key: "{{ docker_gpg_rpm_key_url }}"
    state: present

- name: Add Docker ce repo
  get_url:
    url: "{{ docker_repo_url }}"
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644

- name: Install Docker
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  loop:
  - { name: 'docker-{{ docker_edition }}', state: 'present' }
